- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/config.yml
    - include: tasks/yay.yml
    - include: tasks/alacritty.yml
    - include: tasks/yay-packages.yml
    - include: taks/oh-my-zsh.yml
