---
- name: Clone yay
  git:
    repo: https://github.com/Jguer/yay
    version: master
    dest: /tmp/yay
    clone: yes

- name: Install yay 
  shell:
    cmd:
      makepkg -si
    chdir:
      /tmp/yay
